import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { ArrowUpRight, ChevronLeft, ChevronRight, Clock3, MapPin, Menu, Phone, Star, X } from 'lucide-react'
import { businessData, directionsLink, phoneLink } from './data/businessData'
import { services } from './data/services'
import { gallery } from './data/gallery'
import './footer.css'

const reviews = [
  { name: 'Monika Sewag', stars: 5, text: 'My pre wedding shoot make up was very good thank you antima I love this make up and I love her nature thank you ❤️' },
  { name: 'Ritika Rathi', stars: 5, text: 'Satisfactory Too good ♥️♥️♥️♥️♥️♥️♥️' },
]
const navItems = ['About', 'Services', 'Gallery', 'Reviews', 'Contact']
const fadeUp = { initial: { opacity: 0, y: 24 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, margin: '-80px' }, transition: { duration: .7 } }

function Brand() { return <a className="brand" href="#home"><span>MAKEOVER</span><em>by Antima</em></a> }
function Button({ children, secondary = false, onClick, href }) { const Tag = href ? 'a' : 'button'; return <Tag className={`button ${secondary ? 'button-secondary' : ''}`} onClick={onClick} href={href}>{children}<ArrowUpRight size={16} /></Tag> }
function Navbar({ onBook }) {
  const [open, setOpen] = useState(false)
  return <header className="navbar"><div className="nav-inner"><Brand /><nav className={open ? 'mobile-open' : ''}>{navItems.map(item => <a key={item} href={`#${item.toLowerCase()}`} onClick={() => setOpen(false)}>{item}</a>)}<Button onClick={() => { setOpen(false); onBook() }}>Book Appointment</Button></nav><button className="menu-button" aria-label="Toggle navigation" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button></div></header>
}
function SectionIntro({ eyebrow, title, text }) { return <div className="section-intro"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{text && <p className="intro-copy">{text}</p>}</div> }
function AppointmentModal({ close }) {
  const [sent, setSent] = useState(false)
  return <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && close()}><motion.div className="modal" initial={{ opacity: 0, y: 18, scale: .98 }} animate={{ opacity: 1, y: 0, scale: 1 }}><button className="icon-button close" onClick={close} aria-label="Close"><X /></button>{sent ? <div className="success"><span className="success-mark">✓</span><p className="eyebrow">Request received</p><h2>Thank you!</h2><p>Your appointment request has been received.</p><Button onClick={close}>Close</Button></div> : <><p className="eyebrow">A moment for you</p><h2>Request an appointment</h2><p className="modal-copy">Share a few details and we will be in touch.</p><form onSubmit={e => { e.preventDefault(); setSent(true) }}><input required placeholder="Name" /><input required type="tel" placeholder="Phone Number" /><div className="form-row"><input required type="date" aria-label="Preferred Date" /><select defaultValue=""><option value="" disabled>Service</option>{services.map(service => <option key={service.title}>{service.title}</option>)}</select></div><textarea placeholder="Message" rows="3" /><button className="button" type="submit">Request Appointment <ArrowUpRight size={16} /></button></form></>}</motion.div></div>
}
function App() {
  const [modal, setModal] = useState(false)
  const [lightbox, setLightbox] = useState(null)
  const next = () => setLightbox((lightbox + 1) % gallery.length)
  const prev = () => setLightbox((lightbox - 1 + gallery.length) % gallery.length)
  return <><Navbar onBook={() => setModal(true)} /><main>
    <section className="hero" id="home"><div className="hero-copy"><p className="eyebrow">{businessData.name.toUpperCase()}</p><h1>Your Beauty,<br /><i>Your Moment.</i></h1><p className="hero-text">Beauty, confidence and elegance for every special moment.</p><div className="button-row"><Button onClick={() => setModal(true)}>Book Appointment</Button><Button href={phoneLink} secondary>Call Now</Button></div><p className="location-line"><MapPin size={15} /> Beauty Parlour <span /> Gangashahar, Bikaner</p></div><motion.div className="hero-image" initial={{ opacity: 0, scale: .97 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 1 }}><img src="https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=1200&q=90" alt="Beauty portrait for Makeover by Antima" /><span className="hero-stamp">EST.<br /><b>MB</b><br />BEAUTY</span></motion.div></section>
    <section className="about section" id="about"><motion.div {...fadeUp} className="about-image"><img src="https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1000&q=85" alt="Makeup brushes and cosmetics" /><span className="image-caption">THE ART OF THE DETAIL</span></motion.div><motion.div {...fadeUp} className="about-copy"><SectionIntro eyebrow="A little about us" title="Beauty that makes you feel beautiful" text="Makeover by Antima is a local beauty parlour in Gangashahar, Bikaner, created for the moments when you want to feel especially like yourself." /><div className="feature-list"><div><b>01</b><span>Personal Attention</span></div><div><b>02</b><span>Elegant Beauty Looks</span></div><div><b>03</b><span>Special Occasion Makeup</span></div></div><button className="text-link" onClick={() => document.getElementById('services').scrollIntoView()}>Discover our services <ArrowUpRight size={16} /></button></motion.div></section>
    <section className="services section" id="services"><motion.div {...fadeUp}><SectionIntro eyebrow="The edit" title="Beauty services" text="Everything you need to look and feel your best." /></motion.div><div className="service-grid">{services.map((service, i) => <motion.article {...fadeUp} transition={{ delay: i * .06, duration: .6 }} className="service-card" key={service.title}><img src={service.image} alt={service.title} /><div><span className="card-number">0{i + 1}</span><h3>{service.title}</h3><p>{service.description}</p><button className="text-link" onClick={() => setModal(true)}>Enquire now <ArrowUpRight size={15} /></button></div></motion.article>)}</div><p className="demo-note">Demo services shown for presentation. Enquire for pricing and availability.</p></section>
    <section className="why section"><div className="why-header"><p className="eyebrow">The Antima feeling</p><h2>Your special moments<br /><i>deserve a special look.</i></h2></div><div className="why-grid">{['Personalized Look', 'Elegant Finishing', 'Special Occasion Ready', 'Beauty & Confidence'].map((item, i) => <motion.div {...fadeUp} className="why-item" key={item}><b>0{i + 1}</b><span>{item}</span><ArrowUpRight size={18} /></motion.div>)}</div></section>
    <section className="gallery section" id="gallery"><motion.div {...fadeUp}><SectionIntro eyebrow="The gallery" title="Beauty in every detail" /></motion.div><div className="gallery-grid">{gallery.map((image, i) => <motion.button {...fadeUp} transition={{ delay: i * .05 }} className={`gallery-item item-${i + 1}`} key={image.src} onClick={() => setLightbox(i)}><img src={image.src} alt={image.alt} /><span>View <ArrowUpRight size={15} /></span></motion.button>)}</div></section>
    <section className="reviews section" id="reviews"><div className="rating"><span className="rating-number">3.2</span><div><div className="stars"><Star fill="currentColor" size={17} /><Star fill="currentColor" size={17} /><Star fill="currentColor" size={17} /><Star fill="currentColor" size={17} /><Star fill="currentColor" size={17} /></div><p>10 Google Reviews</p></div></div><div className="review-heading"><p className="eyebrow">Kind words</p><h2>What clients say</h2></div><div className="review-grid">{reviews.map(review => <article className="review-card" key={review.name}><div className="stars">{Array.from({ length: review.stars }, (_, i) => <Star key={i} fill="currentColor" size={15} />)}</div><p>“{review.text}”</p><b>{review.name}</b></article>)}</div></section>
    <section className="cta section"><p className="eyebrow">Make time for you</p><h2>Ready for your <i>makeover?</i></h2><p>Book your appointment and get ready for your next special moment.</p><div className="button-row"><Button onClick={() => setModal(true)}>Book Appointment</Button><Button href={phoneLink} secondary>Call Now</Button></div></section>
    <section className="contact section" id="contact"><div><SectionIntro eyebrow="Find us" title="Visit Makeover by Antima" text="Come by for your next beauty moment in the heart of Gangashahar." /><div className="contact-details"><div><MapPin /><p>{businessData.address.map(line => <span key={line}>{line}</span>)}</p></div><div><Phone /><p><a href={phoneLink}>{businessData.phone}</a></p></div><div><Clock3 /><p>{businessData.openingTime}</p></div></div><div className="button-row"><Button href={phoneLink}>Call Now</Button><Button href={directionsLink} secondary>Get Directions</Button></div></div><div className="map-card"><div className="map-lines" /><MapPin size={28} /><span>{businessData.plusCode}</span><small>Gangashahar · Bikaner</small></div></section>
  </main><footer><Brand /><p>Beauty, confidence & elegance.</p><nav>{['Home', ...navItems].map(item => <a href={`#${item.toLowerCase()}`} key={item}>{item}</a>)}</nav><a className="footer-phone" href={phoneLink}>{businessData.phone}</a><small>© 2026 Makeover by Antima. All rights reserved.</small></footer>
  <AnimatePresence>{modal && <AppointmentModal close={() => setModal(false)} />}{lightbox !== null && <div className="lightbox"><button className="icon-button lightbox-close" onClick={() => setLightbox(null)}><X /></button><button className="lightbox-arrow left" onClick={prev}><ChevronLeft /></button><img src={gallery[lightbox].src} alt={gallery[lightbox].alt} /><button className="lightbox-arrow right" onClick={next}><ChevronRight /></button></div>}</AnimatePresence></>
}
export default App
